// lib/constants.js

export const mkNowMinus = (mins) =>
  new Date(Date.now() - mins * 60 * 1000).toISOString();

// Complete list of component types
export const COMPONENT_TYPES = [
  { id: "PROCESSOR", name: "Processor" },
  { id: "MOTHERBOARD", name: "Motherboard" },
  { id: "GRAPHICS_CARD", name: "Graphics Card" },
  { id: "POWER_SUPPLY", name: "Power Supply" },
  { id: "RAM", name: "RAM" },
  { id: "CPU_COOLER", name: "CPU Cooler" },
  { id: "SSD", name: "SSD" },
  { id: "HDD", name: "HDD" },
  { id: "CABINET", name: "Cabinet" },
  { id: "MONITOR", name: "Monitor" },
  { id: "KEYBOARD", name: "Keyboard" },
  { id: "MOUSE", name: "Mouse" },
  { id: "HEADSET", name: "Headset" },
  { id: "ADDITIONAL_CASE_FANS", name: "Additional Case Fans" },
];

// Dimensions list (Static fallback, though backend sends this too)
export const DIMENSIONS = {
  sockets: [
    { id: "AM4", label: "AM4" },
    { id: "AM5", label: "AM5" },
    { id: "LGA1700", label: "LGA1700" },
  ],
  memoryTypes: [
    { id: "DDR4", label: "DDR4" },
    { id: "DDR5", label: "DDR5" },
  ],
  formFactors: [
    { id: "ATX", label: "ATX" },
    { id: "mATX", label: "mATX" },
    { id: "ITX", label: "ITX" },
  ],
  chipsets: [
    { id: "B650", label: "B650" },
    { id: "X670E", label: "X670E" },
    { id: "Z790", label: "Z790" },
  ],
  pcie: [
    { id: "3", label: "PCIe 3.0" },
    { id: "4", label: "PCIe 4.0" },
    { id: "5", label: "PCIe 5.0" },
  ],
};

export const SOURCES = [
  {
    id: "pcpt",
    name: "PCPriceTracker",
    type: "aggregator",
    baseUrl: "https://pcpricetracker.in",
  },
  {
    id: "md",
    name: "MDComputers",
    type: "vendor",
    baseUrl: "https://mdcomputers.in",
  },
  {
    id: "prime",
    name: "PrimeABGB",
    type: "vendor",
    baseUrl: "https://primeabgb.com",
  },
  { id: "manual", name: "XO Rig Manual", type: "manual", baseUrl: "" },
];

export const VENDORS = [
  { id: "md", name: "MDComputers", trust: 86 },
  { id: "prime", name: "PrimeABGB", trust: 82 },
  { id: "ved", name: "Vedant Computers", trust: 78 },
];

// Core identity field definitions
export const CORE_IDENTITY_FIELDS = [
  { key: "manufacturer", label: "Manufacturer", required: true },
  { key: "vendor", label: "Vendor", required: false, type: "dropdown" },
  { key: "model_name", label: "Model Name", required: true },
  { key: "model_number", label: "Model Number", required: true },
  { key: "product_page_url", label: "Product Page URL", required: false },
  { key: "price", label: "Price", required: false, type: "number" },
  {
    key: "discounted_price",
    label: "Discounted Price",
    required: false,
    type: "number",
  },
];

export const SPEC_DEFS = {
  PROCESSOR: [
    { id: "socket", label: "Socket", type: "string", unit: "" },
    { id: "cores", label: "Cores", type: "int", unit: "" },
    { id: "threads", label: "Threads", type: "int", unit: "" },
    { id: "base_clock", label: "Base Clock", type: "float", unit: "GHz" },
    { id: "boost_clock", label: "Boost Clock", type: "float", unit: "GHz" },
    { id: "tdp_watts", label: "TDP", type: "int", unit: "W" },
    { id: "integrated_gpu", label: "iGPU", type: "bool", unit: "" },
    { id: "includes_cooler", label: "Includes Cooler", type: "bool", unit: "" },
  ],
  MOTHERBOARD: [
    { id: "vrm_phases", label: "VRM Phases", type: "string", unit: "" },
    { id: "m2_slots", label: "M.2 Slots", type: "int", unit: "" },
    { id: "wifi", label: "Wi‑Fi", type: "bool", unit: "" },
    { id: "usb_c_header", label: "USB‑C Header", type: "bool", unit: "" },
  ],
  GRAPHICS_CARD: [
    { id: "vram", label: "VRAM", type: "int", unit: "GB" },
    { id: "boost_mhz", label: "Boost", type: "int", unit: "MHz" },
    { id: "tbp", label: "TBP", type: "int", unit: "W" },
    { id: "slots", label: "Slot Thickness", type: "float", unit: "slots" },
    { id: "length_mm", label: "Length", type: "int", unit: "mm" },
  ],
  RAM: [
    { id: "capacity_gb", label: "Capacity", type: "int", unit: "GB" },
    { id: "sticks", label: "Sticks", type: "int", unit: "" },
    { id: "speed_mhz", label: "Speed", type: "int", unit: "MHz" },
    { id: "cl", label: "CAS Latency", type: "int", unit: "CL" },
  ],
  POWER_SUPPLY: [
    { id: "wattage", label: "Wattage", type: "int", unit: "W" },
    {
      id: "rating",
      label: "80+ Rating",
      type: "enum",
      unit: "",
      enum: ["Bronze", "Gold", "Platinum"],
    },
    {
      id: "atx_version",
      label: "ATX Spec",
      type: "enum",
      unit: "",
      enum: ["ATX 2.52", "ATX 3.0"],
    },
    { id: "pcie_12vhpwr", label: "12VHPWR/12V-2x6", type: "bool", unit: "" },
  ],
  CPU_COOLER: [
    {
      id: "type",
      label: "Cooler Type",
      type: "enum",
      unit: "",
      enum: ["Air", "AIO", "Custom Loop"],
    },
    { id: "height_mm", label: "Height", type: "int", unit: "mm" },
    { id: "radiator_size", label: "Radiator Size", type: "int", unit: "mm" },
  ],
  SSD: [
    { id: "capacity_gb", label: "Capacity", type: "int", unit: "GB" },
    {
      id: "interface",
      label: "Interface",
      type: "enum",
      unit: "",
      enum: ["SATA", "NVMe"],
    },
    {
      id: "form_factor",
      label: "Form Factor",
      type: "enum",
      unit: "",
      enum: ['2.5"', "M.2"],
    },
    {
      id: "gen",
      label: "PCIe Gen",
      type: "enum",
      unit: "",
      enum: ["PCIe 3.0", "PCIe 4.0", "PCIe 5.0"],
    },
  ],
  HDD: [
    { id: "capacity_gb", label: "Capacity", type: "int", unit: "GB" },
    { id: "rpm", label: "RPM", type: "int", unit: "" },
    { id: "cache_mb", label: "Cache", type: "int", unit: "MB" },
    {
      id: "form_factor",
      label: "Form Factor",
      type: "enum",
      unit: "",
      enum: ['3.5"', '2.5"'],
    },
  ],
  CABINET: [
    { id: "max_gpu_mm", label: "Max GPU Length", type: "int", unit: "mm" },
    { id: "max_cooler_mm", label: "Max CPU Cooler", type: "int", unit: "mm" },
    {
      id: "radiator_support",
      label: "Radiator Support",
      type: "string",
      unit: "",
    },
  ],
  MONITOR: [
    { id: "size_inches", label: "Size", type: "float", unit: '"' },
    { id: "resolution", label: "Resolution", type: "string", unit: "" },
    { id: "refresh_rate", label: "Refresh Rate", type: "int", unit: "Hz" },
    { id: "panel_type", label: "Panel Type", type: "string", unit: "" },
    { id: "response_time", label: "Response Time", type: "int", unit: "ms" },
  ],
  KEYBOARD: [
    { id: "switch_type", label: "Switch Type", type: "string", unit: "" },
    { id: "layout", label: "Layout", type: "string", unit: "" },
    { id: "backlit", label: "Backlit", type: "bool", unit: "" },
    { id: "wireless", label: "Wireless", type: "bool", unit: "" },
  ],
  MOUSE: [
    { id: "dpi", label: "DPI", type: "int", unit: "" },
    { id: "sensor_type", label: "Sensor Type", type: "string", unit: "" },
    { id: "wireless", label: "Wireless", type: "bool", unit: "" },
    { id: "buttons", label: "Buttons", type: "int", unit: "" },
  ],
  HEADSET: [
    { id: "driver_size", label: "Driver Size", type: "int", unit: "mm" },
    { id: "impedance", label: "Impedance", type: "int", unit: "Ω" },
    {
      id: "frequency_response",
      label: "Frequency Response",
      type: "string",
      unit: "",
    },
    { id: "wireless", label: "Wireless", type: "bool", unit: "" },
    {
      id: "noise_cancellation",
      label: "Noise Cancellation",
      type: "bool",
      unit: "",
    },
  ],
  ADDITIONAL_CASE_FANS: [
    { id: "size_mm", label: "Size", type: "int", unit: "mm" },
    { id: "speed_rpm", label: "Speed", type: "int", unit: "RPM" },
    { id: "noise_level", label: "Noise Level", type: "float", unit: "dBA" },
    { id: "airflow_cfm", label: "Airflow", type: "float", unit: "CFM" },
  ],
};

export const CATEGORY_COMP_KEYS = {
  PROCESSOR: ["socket"],
  MOTHERBOARD: ["socket", "chipset", "memory_type", "form_factor"],
  GRAPHICS_CARD: ["pcie_generation"],
  POWER_SUPPLY: ["form_factor"],
  RAM: ["memory_type"],
  CPU_COOLER: ["socket"],
  SSD: ["interface", "form_factor"],
  HDD: ["form_factor"],
  CABINET: ["form_factor"],
  MONITOR: [],
  KEYBOARD: [],
  MOUSE: [],
  HEADSET: [],
  ADDITIONAL_CASE_FANS: [],
};

// export const DUMMY_COMPONENTS = [
//   {
//     component_id: "cmp_cpu_7800x3d",
//     category: "CPU",
//     brand: "AMD",
//     model: "Ryzen 7 7800X3D",
//     variant_name: "Tray",
//     release_date: "2023-04-06",
//     warranty_years: 3,
//     ean: "0730143314924",
//     active_status: "active",
//     images: ["https://images.example.com/7800x3d.png"],
//     datasheet_url: "https://example.com/ds/7800x3d",
//     product_page_url: "https://example.com/p/7800x3d",
//     quality: { completeness: 92, needs_review: false, review_status: "approved" },
//     compatibility: { socket: "AM5" },
//     specs: {
//       core_count: { v: 8, source_id: "manual", confidence: 0.98, updated_at: mkNowMinus(3500) },
//       thread_count: { v: 16, source_id: "manual", confidence: 0.98, updated_at: mkNowMinus(3500) },
//       base_clock: { v: 4.2, source_id: "manual", confidence: 0.95, updated_at: mkNowMinus(3500) },
//       boost_clock: { v: 5.0, source_id: "manual", confidence: 0.95, updated_at: mkNowMinus(3500) },
//       tdp: { v: 120, source_id: "manual", confidence: 0.9, updated_at: mkNowMinus(3500) },
//       igpu: { v: true, source_id: "manual", confidence: 0.85, updated_at: mkNowMinus(3500) },
//     },
//     offers: [
//       {
//         offer_id: "off_1",
//         vendor_id: "md",
//         in_stock: true,
//         quantity: 7,
//         price_inr: 34999,
//         shipping_inr: 199,
//         effective_price_inr: 35198,
//         updated_at: mkNowMinus(40),
//         vendor_url: "https://mdcomputers.in/ryzen-7-7800x3d.html",
//         source_id: "pcpt",
//       },
//       {
//         offer_id: "off_2",
//         vendor_id: "prime",
//         in_stock: true,
//         quantity: 3,
//         price_inr: 35999,
//         shipping_inr: 0,
//         effective_price_inr: 35999,
//         updated_at: mkNowMinus(70),
//         vendor_url: "https://primeabgb.com/ryzen-7-7800x3d",
//         source_id: "pcpt",
//       },
//     ],
//     external_ids: [
//       {
//         source_id: "pcpt",
//         external_id: "pcpt:cpu:7800x3d",
//         external_url: "https://pcpricetracker.in/cpu/7800x3d",
//         match_method: "manual",
//         match_confidence: 1.0,
//       },
//     ],
//     audit: [
//       {
//         at: mkNowMinus(1200),
//         actor: "admin@xor",
//         action: "update",
//         field: "specs.tdp",
//         before: "105",
//         after: "120",
//       },
//     ],
//   },
//   {
//     component_id: "cmp_mobo_b650m_pro_rs",
//     category: "Motherboard",
//     brand: "ASRock",
//     model: "B650M Pro RS",
//     variant_name: "WiFi",
//     release_date: "2022-10-10",
//     warranty_years: 3,
//     ean: "4710483941062",
//     active_status: "active",
//     images: ["https://images.example.com/b650m.png"],
//     datasheet_url: "https://example.com/ds/b650m-pro-rs",
//     product_page_url: "https://example.com/p/b650m-pro-rs",
//     quality: { completeness: 84, needs_review: true, review_status: "unreviewed" },
//     compatibility: { socket: "AM5", chipset: "B650", memory_type: "DDR5", form_factor: "mATX" },
//     specs: {
//       vrm_phases: { v: "8+2+1", source_id: "pcpt", confidence: 0.7, updated_at: mkNowMinus(800) },
//       m2_slots: { v: 2, source_id: "pcpt", confidence: 0.8, updated_at: mkNowMinus(800) },
//       wifi: { v: true, source_id: "manual", confidence: 0.95, updated_at: mkNowMinus(2000) },
//       usb_c_header: { v: true, source_id: "pcpt", confidence: 0.65, updated_at: mkNowMinus(800) },
//     },
//     offers: [
//       {
//         offer_id: "off_3",
//         vendor_id: "md",
//         in_stock: true,
//         quantity: 5,
//         price_inr: 14999,
//         shipping_inr: 199,
//         effective_price_inr: 15198,
//         updated_at: mkNowMinus(55),
//         vendor_url: "https://mdcomputers.in/asrock-b650m-pro-rs-wifi.html",
//         source_id: "pcpt",
//       },
//     ],
//     external_ids: [
//       {
//         source_id: "pcpt",
//         external_id: "pcpt:mobo:b650m-pro-rs-wifi",
//         external_url: "https://pcpricetracker.in/mobo/b650m-pro-rs",
//         match_method: "fuzzy",
//         match_confidence: 0.88,
//       },
//     ],
//     audit: [
//       {
//         at: mkNowMinus(300),
//         actor: "system",
//         action: "ingest",
//         field: "offers[0].price_inr",
//         before: "15499",
//         after: "14999",
//       },
//     ],
//   },
//   {
//     component_id: "cmp_gpu_4070s_dual_oc",
//     category: "GPU",
//     brand: "ASUS",
//     model: "GeForce RTX 4070 Super",
//     variant_name: "DUAL OC",
//     release_date: "2024-01-17",
//     warranty_years: 3,
//     ean: "4711387422222",
//     active_status: "active",
//     images: ["https://images.example.com/4070s.png"],
//     datasheet_url: "https://example.com/ds/4070s-dual-oc",
//     product_page_url: "https://example.com/p/4070s-dual-oc",
//     quality: { completeness: 88, needs_review: false, review_status: "approved" },
//     compatibility: { pcie_generation: "4" },
//     specs: {
//       vram: { v: 12, source_id: "manual", confidence: 0.95, updated_at: mkNowMinus(1500) },
//       boost_mhz: { v: 2550, source_id: "pcpt", confidence: 0.75, updated_at: mkNowMinus(900) },
//       tbp: { v: 220, source_id: "manual", confidence: 0.9, updated_at: mkNowMinus(1500) },
//       slots: { v: 2.56, source_id: "manual", confidence: 0.9, updated_at: mkNowMinus(1500) },
//       length_mm: { v: 267, source_id: "manual", confidence: 0.9, updated_at: mkNowMinus(1500) },
//     },
//     offers: [
//       {
//         offer_id: "off_4",
//         vendor_id: "prime",
//         in_stock: false,
//         quantity: 0,
//         price_inr: 62999,
//         shipping_inr: 0,
//         effective_price_inr: 62999,
//         updated_at: mkNowMinus(25),
//         vendor_url: "https://primeabgb.com/asus-4070-super-dual-oc",
//         source_id: "pcpt",
//       },
//       {
//         offer_id: "off_5",
//         vendor_id: "ved",
//         in_stock: true,
//         quantity: 2,
//         price_inr: 63999,
//         shipping_inr: 150,
//         effective_price_inr: 64149,
//         updated_at: mkNowMinus(31),
//         vendor_url: "https://vedantcomputers.com/asus-4070-super-dual-oc",
//         source_id: "pcpt",
//       },
//     ],
//     external_ids: [
//       {
//         source_id: "pcpt",
//         external_id: "pcpt:gpu:asus-4070s-dual-oc",
//         external_url: "https://pcpricetracker.in/gpu/4070s-dual-oc",
//         match_method: "ean",
//         match_confidence: 0.97,
//       },
//     ],
//     audit: [
//       {
//         at: mkNowMinus(20),
//         actor: "system",
//         action: "ingest",
//         field: "offers[1].in_stock",
//         before: "false",
//         after: "true",
//       },
//     ],
//   },
//   {
//     component_id: "cmp_ram_32_ddr5_6000",
//     category: "RAM",
//     brand: "G.Skill",
//     model: "Trident Z5 Neo",
//     variant_name: "32GB (2x16) 6000 CL30",
//     release_date: "2022-09-01",
//     warranty_years: 10,
//     ean: "4713294233333",
//     active_status: "active",
//     images: ["https://images.example.com/z5neo.png"],
//     datasheet_url: "https://example.com/ds/z5neo",
//     product_page_url: "https://example.com/p/z5neo",
//     quality: { completeness: 90, needs_review: false, review_status: "approved" },
//     compatibility: { memory_type: "DDR5" },
//     specs: {
//       capacity_gb: { v: 32, source_id: "manual", confidence: 0.9, updated_at: mkNowMinus(1900) },
//       sticks: { v: 2, source_id: "manual", confidence: 0.9, updated_at: mkNowMinus(1900) },
//       speed_mhz: { v: 6000, source_id: "pcpt", confidence: 0.8, updated_at: mkNowMinus(1000) },
//       cl: { v: 30, source_id: "pcpt", confidence: 0.7, updated_at: mkNowMinus(1000) },
//     },
//     offers: [
//       {
//         offer_id: "off_6",
//         vendor_id: "md",
//         in_stock: true,
//         quantity: 9,
//         price_inr: 11999,
//         shipping_inr: 0,
//         effective_price_inr: 11999,
//         updated_at: mkNowMinus(80),
//         vendor_url: "https://mdcomputers.in/gskill-z5neo-32-6000.html",
//         source_id: "pcpt",
//       },
//     ],
//     external_ids: [],
//     audit: [],
//   },
// ];

export const DUMMY_RULES = [
  {
    rule_id: "r1",
    name: "CPU socket must match motherboard socket",
    severity: "error",
    applies: "CPU + Motherboard",
    expr: { op: "eq", left: "cpu.socket", right: "mobo.socket" },
    message: "CPU socket and Motherboard socket must match.",
    enabled: true,
  },
  {
    rule_id: "r2",
    name: "RAM memory type must match motherboard memory type",
    severity: "error",
    applies: "RAM + Motherboard",
    expr: { op: "eq", left: "ram.memory_type", right: "mobo.memory_type" },
    message: "RAM type (DDR4/DDR5) must match the motherboard.",
    enabled: true,
  },
  {
    rule_id: "r3",
    name: "GPU length must fit case max GPU length",
    severity: "warn",
    applies: "GPU + Case",
    expr: { op: "lte", left: "gpu.length_mm", right: "case.max_gpu_mm" },
    message: "GPU length may not fit the selected case.",
    enabled: true,
  },
];
